/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Concepto;
import clases.Producto;
import client.cliente_concepto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuanLH
 */
public class BuscarConcepto extends javax.swing.JDialog {

    /**
     * Creates new form BuscarConcepto
     */
    
    
    public BuscarConcepto() {
        initComponents();
        llenar_tabla();
    }
    
    public BuscarConcepto(JFrame parent){
        super(parent,true);
        initComponents();
        llenar_tabla();
    }
    
    public BuscarConcepto(JDialog parent){
        super(parent,true);
        initComponents();
        llenar_tabla();
    }
    
    public ArrayList<Concepto> traer_data(){
        ArrayList<Concepto> lista=new ArrayList();
        try {
            lista = cliente_concepto.buscar_concepto();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error Conectando al servidor \n",
                    "Informacion", JOptionPane.ERROR_MESSAGE);
        }
        return lista;
    }
    
    public void llenar_tabla(){
        ArrayList<Concepto> lista = traer_data();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] col = {"ID","DESCRIPCION"};
        // ciclo for para agregar cada una de las columnas
        for (int i = 0; i < col.length; i++) {
            modelo.addColumn(col[i]);
        }
        
        int k;
        for(Concepto c:lista){
            k=0;
            Object[] fila = new Object[2];//El tamaño del vector sera la cantidad de columnas de la tabla
            fila[k++] = (Object)c.getId_concepto();
            fila[k++] = (Object)c.getDescripcion();

            modelo.addRow(fila);
        }
        tbConcepto.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConcepto = new javax.swing.JTable();
        btnElegir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Concepto");

        tbConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConceptoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConcepto);

        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElegir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElegir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConceptoMouseClicked
        // TODO add your handling code here:
        btnElegir.setEnabled(true);
    }//GEN-LAST:event_tbConceptoMouseClicked

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        // TODO add your handling code here:
        Concepto c = new Concepto();
        c.setId_concepto((int)tbConcepto.getModel().getValueAt(tbConcepto.getSelectedRow(), 0));
        c.setDescripcion((String)tbConcepto.getModel().getValueAt(tbConcepto.getSelectedRow(), 1));
        Concepto.concepto = c;//Guardando en la variable static para poder buscarla desde el otro form
        this.dispose();
    }//GEN-LAST:event_btnElegirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarConcepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConcepto;
    // End of variables declaration//GEN-END:variables
}
